services:
  app:
    build: ./e-commerce
    volumes:
      - ./e-commerce:/e-commerce
    ports:
      - 8000:8000
    depends_on:
      - mongo
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=Ecommerce.settings

  mongo:
    image: mongo:6.0
    volumes:
      - ./datos:/data/db
    ports:
      - 27017:27017

  restore:
    image: mongo:6.0
    volumes:
      - ./backups:/backups
      - ./e-commerce:/e-commerce
      - ./backup_restore.sh:/backup_restore.sh
    depends_on:
      - mongo
    entrypoint: [ "sh", "/backup_restore.sh" ]
